version: "3.7"
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./docs:/app/docs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DB_ENGINE=django.contrib.gis.db.backends.postgis
      - DB_NAME=drivebc
      - DB_USER=drivebc
      - DB_PASSWORD=Passw0rd!
      - DB_HOST=db
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: /start.sh

  react:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=openssl-legacy-provider
    depends_on:
      - django
    command: npm start

  db:
    image: postgis/postgis:15-3.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=drivebc
      - POSTGRES_USER=drivebc
      - POSTGRES_PASSWORD=Passw0rd!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
