version: "3.7"

x-function: &backend
  build:
    context: .
    dockerfile: ./compose/backend/Dockerfile

  volumes:
    - ./backend:/app/backend
    - ./docs:/app/docs
  environment:
    - DJANGO_SETTINGS_MODULE=config.settings.development
    - DB_ENGINE=django.contrib.gis.db.backends.postgis
    - DB_NAME=drivebc
    - DB_USER=drivebc
    - DB_PASSWORD=Passw0rd!
    - DB_HOST=db
    - DRIVEBC_ROUTE_PLANNER_API_AUTH_KEY=GIPS68ey7YBSIs22RPYJo2lGZ1ASxfSf
    - REDIS_HOST=drivebc_redis
  stdin_open: true
  tty: true
  depends_on:
    - db
    - redis

volumes:
  mailhogdata:
  redisdata:
  db_data:
    driver: local

services:
  django:
    <<: *backend
    container_name: drivebc_backend
    ports:
      - "8000:8000"
    command: /start.sh

  react:
    container_name: drivebc_frontend
    build:
      context: ./frontend
      dockerfile: ../compose/frontend/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=openssl-legacy-provider
    depends_on:
      - django
    command: npm start

  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: drivebc_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=drivebc
      - POSTGRES_USER=drivebc
      - POSTGRES_PASSWORD=Passw0rd!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  worker:
    <<: *backend
    container_name: drivebc_worker
    image: drivebc_worker
    command: /start-worker

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: drivebc_mailhog
    environment:
      MH_STORAGE: maildir
    volumes:
      - mailhogdata:/maildir

  redis:
    image: "redis:6.2"
    container_name: drivebc_redis
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
